alter table PDISCHEDULER_TASK add constraint FK_PDISCHEDULER_TASK_PROJECT foreign key (PROJECT_ID) references PDISCHEDULER_PROJECT(ID);
alter table PDISCHEDULER_TASK add constraint FK_PDISCHEDULER_TASK_PREV_TASK foreign key (PREV_TASK_ID) references PDISCHEDULER_TASK(ID);
create index IDX_PDISCHEDULER_TASK_PROJECT on PDISCHEDULER_TASK (PROJECT_ID);
create index IDX_PDISCHEDULER_TASK_PREV_TASK on PDISCHEDULER_TASK (PREV_TASK_ID);
