alter table PDISCHEDULER_TASK add constraint FK_PDISCHEDULER_TASK_LAST_TASK_RUN foreign key (LAST_TASK_RUN_ID) references PDISCHEDULER_TASK_RUN(ID);
create index IDX_PDISCHEDULER_TASK_LAST_TASK_RUN on PDISCHEDULER_TASK (LAST_TASK_RUN_ID);
