alter table PDISCHEDULER_TASK_RUN add constraint FK_PDISCHEDULER_TASK_RUN_TASK foreign key (TASK_ID) references PDISCHEDULER_TASK(ID);
create index IDX_PDISCHEDULER_TASK_RUN_TASK on PDISCHEDULER_TASK_RUN (TASK_ID);
