-- begin PDISCHEDULER_PROJECT
alter table PDISCHEDULER_PROJECT add constraint FK_PDISCHEDULER_PROJECT_ON_WORKER foreign key (WORKER_ID) references PDISCHEDULER_WORKER(ID)^
create unique index IDX_PDISCHEDULER_PROJECT_UK_NAME on PDISCHEDULER_PROJECT (NAME) where DELETE_TS is null ^
create index IDX_PDISCHEDULER_PROJECT_ON_WORKER on PDISCHEDULER_PROJECT (WORKER_ID)^
-- end PDISCHEDULER_PROJECT
-- begin PDISCHEDULER_TASK
alter table PDISCHEDULER_TASK add constraint FK_PDISCHEDULER_TASK_ON_PROJECT foreign key (PROJECT_ID) references PDISCHEDULER_PROJECT(ID)^
alter table PDISCHEDULER_TASK add constraint FK_PDISCHEDULER_TASK_ON_PREV_TASK foreign key (PREV_TASK_ID) references PDISCHEDULER_TASK(ID)^
create unique index IDX_PDISCHEDULER_TASK_UNQ on PDISCHEDULER_TASK (PROJECT_ID, NAME) where DELETE_TS is null ^
create index IDX_PDISCHEDULER_TASK_ON_PROJECT on PDISCHEDULER_TASK (PROJECT_ID)^
create index IDX_PDISCHEDULER_TASK_ON_PREV_TASK on PDISCHEDULER_TASK (PREV_TASK_ID)^
-- end PDISCHEDULER_TASK
-- begin PDISCHEDULER_TASK_RUN
alter table PDISCHEDULER_TASK_RUN add constraint FK_PDISCHEDULER_TASK_RUN_TASK foreign key (TASK_ID) references PDISCHEDULER_TASK(ID)^
create index IDX_PDISCHEDULER_TASK_RUN_TASK on PDISCHEDULER_TASK_RUN (TASK_ID)^
-- end PDISCHEDULER_TASK_RUN
-- begin PDISCHEDULER_WORKER
create unique index IDX_PDISCHEDULER_WORKER_UK_NAME on PDISCHEDULER_WORKER (NAME) where DELETE_TS is null ^
-- end PDISCHEDULER_WORKER
